projects:
  sporden:
    schemaPath: Sporden\src\main\graphql\schema.json
    includes:
      - Sporden\src\main\graphql\**\*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: android
        generatedFileName: ''
        docsFilePath: Sporden\src\main\graphql\com\amazonaws\amplify\generated\graphql
        graphQLApiId: 2pxfph7wurg2hatfu36n6vpngm
        maxDepth: 2
      endpoints:
        prod: >-
          https://d2uobknvv5dxfparhmici5o27y.appsync-api.us-east-1.amazonaws.com/graphql
